checks:
    javascript: true

build:
    environment:
        node: v10.16.0

    filter:
        excluded_paths:
            - tests/*
            - scripts/*

    dependencies:
        #before:
            #- npm install istanbul   # or add it as part of your package.json

    tests:
        before:
            command: 'chown -R $USER:$USER db/*'
            command: 'chmod +x db/reset_test_db.bash'
        override:
            - js-scrutinizer-run
                #command: 'istanbul cover --report clover test.js'
                #command: 'npm run test-scrutinizer'
                command: 'npm run pretest'
                command: 'npm test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
